# Generated by Django 2.2.9 on 2019-12-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(default='', max_length=254)),
                ('review', models.TextField()),
                ('score', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
